// Narration / speaker notes — walkthrough of the hybrid AI trial-operations layer.
module.exports = [
  // 1 Title
  "This walks through a hybrid AI trial-operations layer — an agentic system, built on the Claude-plus-local stack, that handles the project management, trial management, and monitoring work across a study. Seventy-five automations: recurrent QC checks, document and SOP ingestion, eTMF filing, Smartsheet timeline updates, and risk-based monitoring. And one principle holds throughout: the AI drafts, triages, and routes; validated tools and humans own every regulated number and record.",
  // 2 Problem
  "Trial operations are fragmented. The knowledge and the work are spread across the EDC, the eTMF, Smartsheet, Pinnacle 21, email, and a dozen SOPs — and the team spends its time on manual QC triage, document filing, status decks, and chasing action items. It is exactly the kind of repetitive, cross-system busywork that an AI layer can absorb — if, and only if, it is governed properly.",
  // 3 The idea
  "So we point the hybrid stack at operations. Seventy-five governed agents, each one routed by data sensitivity, tiered by risk, and gated by a human. The AI reads your systems, reasons over de-identified text on Claude or sensitive data on the local model, and proposes a change — but nothing regulated moves until a person approves it, with a full Part 11 audit trail.",
  // 4 Architecture
  "Here is how it is wired. An orchestrator fires agents on a schedule or on study events. Every agent calls one gateway, which routes by data classification, runs the Presidio guardrail that blocks patient data from the cloud, and logs everything. Behind it sit three things: the local model for sensitive data, the Claude API for de-identified reasoning, and a RAG knowledge base of your SOPs and study docs. Connectors expose your systems as tools. And every regulated change lands in a human-approval queue before it is written.",
  // 5 Governance
  "The governance is the whole point. Three tiers: green for drafts and cited answers; amber for triage and proposed changes with a human verify; red for anything touching a reported number, a record of truth, or unblinded data — where a validated tool and a human decide, and the model is out of the path. Three hard rules: patient data never leaves the local model; every reported number comes from a validated tool; and a human approves every change to a regulated record or timeline.",
  // 6 PM / timeline
  "Take project management. When a data cut is declared, an agent recomputes the critical path in Smartsheet, sees what is now driving the finish date, drafts the you-are-now-blocked notifications, and posts the recomputed plan to the approval queue. Smartsheet's engine does the math; the AI explains and proposes; the project manager approves before any committed date is written. And the weekly status report drafts itself from the plan of record.",
  // 7 eTMF / docs
  "On documents: agents auto-classify incoming files to the TMF Reference Model, flag missing or expiring documents, and propose filings, which the document controller approves. And every approved SOP and work instruction is ingested into the knowledge base — so anyone can ask, what does our SOP require for a derived-variable spec, and get the exact clause, cited.",
  // 8 Data QC
  "This is the marquee one — recurrent data-validity QC at every stage. Each night, after a new dataset build, Pinnacle 21 produces the authoritative conformance findings. The local agent then clusters them, diffs against the last clean run to surface only what is genuinely new, drafts a disposition grounded in the reviewer guides, and routes each one to the right programmer. It never changes a verdict. A four-hour manual triage becomes a clean, pre-explained queue at eight a.m.",
  // 9 Monitoring / RBQM
  "For monitoring, under ICH E6(R3) risk-based quality management: agents watch the key risk indicators and quality tolerance limits, detect breaches and central-monitoring signals like site outliers or enrollment anomalies, surveil protocol deviations, and assemble the DSMB packet. Unblinded signals run on the local model; the reported safety numbers come from validated tools with medical review.",
  // 10 Agent loop
  "Every agent follows the same loop, and it is worth seeing once. A trigger fires; the agent gathers context from your systems and the cited knowledge base; it classifies the data and routes to local or cloud; it drafts, triages, or summarizes; it proposes the change to the human queue with its rationale and sources; and only on approval is anything written to the system of record — all of it logged. That loop is what makes seventy-five different automations safe and consistent.",
  // 11 Roadmap
  "You build it in stages, and you start small. Phase zero is the stack — gateway, local model, Claude under a BAA, the guardrail and the approval queue. Phase one is the knowledge base — ingest the SOPs and ship the compliance Q&A agent first; it is pure green, cited, and instantly useful. Phase two adds read-only connectors and the nightly QC-triage and weekly status agents. Phase three turns on the event-driven automations and the monitoring signals. Each agent earns lighter review as it builds a track record.",
  // 12 Worked example
  "A day in the layer: at two a.m. the QC agent surfaces three genuinely new findings among two hundred forty and pre-triages the rest. At ten-thirty a data cut fires and the timeline cascade updates in minutes. At one p.m. a key risk indicator breaches and the signal is drafted for the monitor. At three, a programmer gets an SOP answer, cited, in seconds, and three documents are filed to the eTMF on approval. At four, the weekly status report drafts itself. Every regulated number came from a validated system; no patient data left the building; a human approved every committed change.",
  // 13 Recap
  "So that is the operations layer. Seventy-five governed automations on the hybrid stack, absorbing the cross-system busywork while validated tools and humans keep ownership of everything that is regulated. Start with the knowledge base and the SOP agent, keep everything behind the approval queue, and expand as trust grows. The full catalog — every automation, its engine, its integration, and its human checkpoint — is in the operating wiki alongside this. Thank you.",
];
