// Append the Optimal-Transport + Active-Inference (nested/meta) early-warning signals to _catalog.json.
const fs = require("fs");
const C = JSON.parse(fs.readFileSync(__dirname + "/_catalog.json", "utf8"));

const adv = {
  participant: [
    { name: "Wasserstein drift vs pooled reference", category: "OT · drift", signal: "Continuous geometry-aware precursor: how far a participant's evolving LFT/ECG/PK distribution has moved from the pooled reference (a Wasserstein barycenter of prior cohorts) — rises before any rule threshold is crossed.", data_source: "central-lab / ECG / PK streams (on-device)", detection: "Optimal Transport: (sliced-)Wasserstein distance, participant vs reference; the transport map localizes WHICH grades/exposures drive the shift. Decision-support — flags for review, makes no determination.", engine: "On-device local LLM", threshold: "W-distance leaves its control band, trending toward worsening (complements the rule-based DLT/Hy's-Law triggers)", action: "Early flag to medical monitor; intensify monitoring on the implicated measures", severity: "AMBER — continuous precursor, earlier than a threshold rule", adv: true },
    { name: "Free-energy spike (participant generative model)", category: "Active inference", signal: "Bayesian surprise: how unexpected a participant's observations are under the model of their expected trajectory. A spike = the participant is deviating from expectation — anticipatory, before a frank event.", data_source: "participant safety/PK observations (on-device)", detection: "Active inference: variational free energy (negative log model-evidence), precision-weighted per participant. Decision-support only.", engine: "On-device local LLM", threshold: "Free-energy exceeds its rolling band", action: "Flag for medical-monitor review; raise the participant's monitoring precision", severity: "AMBER — anticipatory deviation signal", adv: true },
    { name: "EFE-recommended monitoring action (active sampling)", category: "Active inference", signal: "The agent computes Expected Free Energy over candidate observations (e.g. an unscheduled LFT/ECG/PK draw) and recommends the one that would most reduce uncertainty about emerging DLT/safety risk — proactive, not reactive.", data_source: "participant state + protocol-allowed assessments", detection: "Active inference EFE = epistemic (information-gain) + pragmatic (reach the preferred/safe state) value. A SUGGESTION for human approval — never an autonomous clinical or dosing action.", engine: "On-device local LLM", threshold: "EFE-optimal action exceeds a value-of-information threshold", action: "Recommend the data-collection action to the medical monitor for approval", severity: "AMBER — proactive monitoring recommendation", adv: true },
  ],
  study: [
    { name: "Cohort distributional shift across escalating doses (Wasserstein)", category: "OT · drift", signal: "W₂ distance between the current cohort's safety/exposure distribution and the prior-cohort barycenter — quantifies the dose-escalation safety shift continuously and is sensitive to TAIL mass moving (the dangerous part), which mean-threshold rules miss.", data_source: "aggregate (de-identified) cohort safety/PK", detection: "Optimal Transport on aggregate distributions; the transport plan shows which severity grades / exposure ranges drive the shift.", engine: "Cloud Claude (aggregate) · on-device for participant-level", threshold: "W-distance trend exceeds the cohort-to-cohort control band", action: "Surface to the SRC ahead of the escalation review", severity: "AMBER — continuous dose-escalation safety drift", adv: true },
    { name: "Study-level free-energy drift (model evidence)", category: "Active inference", signal: "Surprise of aggregate trajectories (enrollment, AE rate, data quality) vs the pooled expected-study model; a sustained rise = the study departing from its expected course.", data_source: "aggregate study KRIs", detection: "Active inference at the study level; the QTLs encode the 'preferred' states (prior preferences C). Free energy over aggregate states.", engine: "Cloud Claude", threshold: "Sustained free-energy rise above band", action: "PM review; SRC if safety-driven", severity: "AMBER — futility / safety / feasibility precursor", adv: true },
    { name: "EFE-guided risk-based monitoring allocation", category: "Active inference", signal: "Precision-weighted EFE recommends which site/cohort to monitor next to most reduce risk uncertainty — anticipatory RBM that focuses effort where information-gain is highest.", data_source: "site/cohort KRIs + uncertainty", detection: "Active inference precision/EFE ranks monitoring targets; decision-support for the monitoring plan.", engine: "Cloud Claude", threshold: "EFE ranking of targets", action: "Feed the risk-based monitoring plan; CRA tasking (human-approved)", severity: "GREEN — optimization of effort, not a risk itself", adv: true },
    { name: "Site data-distribution anomaly (Optimal Transport)", category: "OT · quality", signal: "Wasserstein distance of a site's data distribution from the pooled barycenter flags central-monitoring outliers — digit preference, variance anomalies, possible fabrication.", data_source: "per-site aggregate (de-identified) data", detection: "OT distance, site vs pool; a large distance = outlier site. Decision-support; triggers for-cause review.", engine: "Cloud Claude (de-identified)", threshold: "Site W-distance beyond the pool's tolerance", action: "Flag for central-monitoring / for-cause review", severity: "AMBER — data-integrity early warning", adv: true },
  ],
  client: [
    { name: "Sponsor-behavior drift (Wasserstein)", category: "OT · drift", signal: "W distance of the sponsor's recent engagement / payment / scope distribution vs their historical baseline barycenter — a continuous relationship-drift signal earlier than any single threshold.", data_source: "CRM / finance-AR / comms metadata (non-sensitive)", detection: "Optimal Transport on engagement features; a rising distance = the relationship cooling.", engine: "Cloud Claude", threshold: "W-distance beyond the baseline band", action: "Account / BD lead review", severity: "AMBER — commercial early warning", adv: true },
    { name: "Program-level free-energy (commercial surprise)", category: "Active inference", signal: "Surprise of the program trajectory (milestones, comms cadence, AR) vs the expected-sponsor model — the top of the hierarchy; an early commercial-risk signal.", data_source: "program milestones / comms / AR", detection: "Active inference at the client level; decision-support for the account team.", engine: "Cloud Claude", threshold: "Sustained free-energy rise", action: "Account lead + leadership review", severity: "AMBER — program/contract-risk precursor", adv: true },
  ],
  platform: [
    { name: "Pooled reference priors — Wasserstein barycenters (empirical-Bayes pooling)", category: "Cross-study pooling", signal: "The system maintains Wasserstein barycenters of prior cohorts/studies as the reference priors each tier compares against; higher tiers learn the lower tiers' priors (empirical Bayes), so a new cohort/study starts with population-informed expectations and recalibrates as studies complete.", data_source: "historical cohorts/studies (per-tier sensitivity)", detection: "OT barycenters + hierarchical / empirical-Bayes priors updated across studies — the cross-study pooling loop that sets every tier's reference.", engine: "On-device (sensitive) / cloud (non-sensitive), per tier", threshold: "n/a", action: "Sets each tier's reference; recalibrated as studies complete", severity: "the meta layer", adv: true },
    { name: "Nested (deep) active-inference hierarchy — participant → study → client", category: "Active inference", signal: "A hierarchical generative model: each tier's beliefs are top-down priors for the tier below; bottom-up prediction errors (surprise) propagate up across timescales (fast participant → slow client). Free energy is minimized jointly, so a participant DLT mechanically raises study- and program-level risk.", data_source: "all tiers", detection: "Deep / hierarchical active inference; a Wasserstein-regularized free energy ties the levels and the pooled priors together.", engine: "per tier (on-device + cloud)", threshold: "n/a", action: "The nested loop; surfaces tier-coupled early warnings", severity: "the architecture", adv: true },
  ],
};
["participant", "study", "client", "platform"].forEach(k => { C[k].signals = C[k].signals.concat(adv[k]); });
fs.writeFileSync(__dirname + "/_catalog.json", JSON.stringify(C, null, 2));
const t = C.participant.signals.length + C.study.signals.length + C.client.signals.length;
console.log("appended advanced signals. participant:", C.participant.signals.length, "study:", C.study.signals.length, "client:", C.client.signals.length, "platform:", C.platform.signals.length, "| total signals:", t);
