// Spoken narration for the Risk-EarlyWarning walkthrough — one entry per slide (first-person, natural).
module.exports = [
  // 1 · title
  "This is a short walkthrough of the trial-risk early-warning dashboard. The idea is simple: catch the risk that a trial might have to stop — early, and across three levels: the individual participant, the study as a whole, and the client relationship. It runs on a hybrid of cloud Claude (under a BAA) and on-device local models. And throughout, the AI only detects, aggregates, and triages. It never makes the safety or termination call. Let me show you how it works.",
  // 2 · the problem
  "Early-phase trials can stop for reasons that build up quietly. A participant's safety signal. A cohort's toxicity creeping toward the stopping rule. Or a sponsor going cold on the program. The trouble is that the first formal look is often the cohort review or a governance meeting — and by then we are days or weeks behind. The dashboard watches all three of these continuously, so the earliest mover is visible long before that meeting.",
  // 3 · dashboard at a glance
  "Here is the dashboard itself. Three panels — participant, study, and client — each with a simple red, amber, green status, the top signals underneath, and the engine that powers it. Below the panels is a live early-warning feed. Right now everything is amber: a candidate liver signal on one participant, an enrollment limit breached at the study level, and a payment-aging flag on the client side. Each panel rolls its signals up to a status — but that status is a prompt for a human, not a verdict the system reaches on its own.",
  // 4 · participant tier
  "The participant tier is the most sensitive, so it runs entirely on-device, with zero egress. It flags candidate dose-limiting toxicities inside the evaluation window: Hy's-Law liver signals, QTc prolongation, PK exposures beyond the safety margin, and escalating adverse-event clusters. The key word is early. It surfaces the pattern and pre-assembles the safety-committee packet before the formal cohort review. What it does not do is adjudicate the toxicity. That is the medical monitor and the Safety Review Committee.",
  // 5 · study tier
  "The study tier watches the trial's trajectory against its own rules: the cohort toxicity rate against the stopping rule, enrollment and screen-failure limits, the safety quality-tolerance limits from ICH, and central data-quality signals. These are de-identified, aggregate numbers, so they run on cloud Claude — with any participant-level drill-down dropping back to the on-device model. The project manager owns these calls, with the safety committee on anything safety-related.",
  // 6 · client tier
  "The third tier is the commercial one — the early warning that a sponsor might cancel, de-scope, or not renew. Payment aging, a drop in communication, scope-reduction change orders, and the sponsor's own financial and pipeline health. This is non-sensitive business data, so it sits on cloud Claude. And I want to be clear about what this tier is. It is decision-support for the account team, surfacing signals. It is never a judgment the system makes about a sponsor.",
  // 7 · architecture & governance
  "Underneath, one rule decides where everything runs: sensitivity. Participant-level safety and unblinded data go to the on-device model, and never leave the validated environment. Non-sensitive, aggregate operational and commercial data go to cloud Claude, under a business-associate agreement. And here is the rule that governs the whole thing. The AI flags, aggregates, triages, and drafts the alert — it never makes the safety or termination call. The reported numbers come from the validated safety database, never the model. Every flag triggers a human review and a logged disposition, and nothing is paused or terminated by the system itself.",
  // 8 · advanced engine
  "There is an optional advanced layer for teams that want it. Instead of waiting for a threshold to be crossed, it watches for drift and surprise. Optimal transport measures how far a distribution has moved from a learned reference, in a way that respects clinical severity. Active inference treats the monitor as a model of the expected trajectory, so rising surprise is itself an early warning — and it can even recommend the most informative next test to run. It is decision-support only: the threshold rules stay authoritative, the methods were independently checked, and it is validated and frozen before it ever informs a regulated decision.",
  // 9 · worked example
  "Here is how it comes together. Day nine of cohort four: a participant's labs post a Hy's-Law pattern. The on-device model recognizes it, and because it is inside the evaluation window, flags a candidate toxicity — without any data leaving the device. Within minutes it assembles the case and routes it to the medical monitor and the committee chair, ahead of the scheduled review. The humans take it from there: a confirmatory test, the committee convenes, dosing pauses per protocol. The payoff is the timing. This surfaced on day nine, not at the cohort meeting on day twenty-one — with the packet already built, and a human making every call.",
  // 10 · standing it up
  "Building it is staged. First, the safe wins: wire the study and client tiers from existing operational and commercial feeds into cloud Claude, behind a human-review queue, with de-identified data only. Second, the on-device participant tier in the validated environment, with the safety logic encoded and alerting wired to the medical monitor. Third, the scoring, escalation, and audit trail — and, optionally, the advanced engine, validated and frozen before it informs anything. Each phase delivers value on its own.",
  // 11 · close
  "So, in one line: catch termination risk before the meeting, and let humans make every call. It is earlier — a liver signal on day nine, not day twenty-one. It is three tiers on one screen. It is governed by design — sensitive data on-device, validated tools owning the numbers, and the committees and project managers deciding. And it fits the program: a phase-one pilot deliverable on the same hybrid stack — no new principle, just a new target. Thanks for watching.",
];
